<?php
# 2024-06-10
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/product/list.phtml`":
# https://github.com/cabinetsbay/catalog/issues/38
use Magento\Framework\App\Action\Action;

/**
 * Product list template
 *
 * @var $block \Sharapov\Cabinetsbay\Block\Product\ListProduct
 */
$_productCollection = $block->getLoadedProductCollection();
// Show products list only on 3rd category level
if ($block->level() >= 3) :
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	if (! $_productCollection->count()): ?>
		<div class="message info empty">
			<div><?= /* @escapeNotVerified */
				__('We can\'t find products matching the selection.') ?></div>
		</div>
	<?php else: ?>
		<?= $block->getToolbarHtml() ?>
		<?= $block->getAdditionalHtml() ?>
		<?php
		if ($block->getMode() == 'grid') {
			$viewMode = 'grid';
			$imageDisplayArea = 'category_page_grid';
			//$showDescription = false;
			$templateType
				= \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
		} else {
			$viewMode = 'list';
			$imageDisplayArea = 'category_page_list';
			//$showDescription = true;
			$templateType
				= \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
		}
		/**
		 * Position for actions regarding image size changing in vde if needed
		 */
		$pos = $block->getPositioned();
		?>
		<div class="products wrapper <?= $viewMode ?> products-<?= $viewMode ?>">
			<?php
				/**
				 * 2024-03-10
				 * 1.1) Level 0: «Root Catalog».
				 * 1.2) Level 1: «Default Category».
				 * 1.3) Level 2:
				 * 		«Ready to Assemble Cabinets»
				 * 		«Pre-Assembled Cabinets»
				 * 		«Cabinet Organizers & Hardware»
				 * 2024-06-10
				 * 1) "Handle category levels > 3": https://github.com/cabinetsbay/catalog/issues/36
				 * 2.1) Level 4: https://localhost.com:2255/ready-to-assemble-cabinets/croydon-white-shaker/pantry-oven-cabinets.html
				 * 2.2) Level 5: https://localhost.com:2255/ready-to-assemble-cabinets/croydon-white-shaker/pantry-oven-cabinets/pantry-cabinets.html
				 */
				if (df_category_level($block->getCurrentCategory()) > 3) { ?>
					<h3><?=$block->getCurrentCategory()->getName(); ?></h3>
		  		<?php } ?>
			<ol class="products list items product-items">
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php foreach ($_productCollection as $_product): ?>
					<li class="item product product-item">
						<div class="product-item-info"
							 data-container="product-<?= /* @escapeNotVerified */
							 $viewMode ?>">
							<?php
							$productImage = $block->getImage($_product,
								$imageDisplayArea);
							if ($pos != null) {
								$position = ' style="left:'
									. $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight()
									. 'px;"';
							}
							?>
							<?php
							$_productNameStripped
								= $block->stripTags($_product->getName(),
								null, true);
							?>
							<strong class="product name product-item-name product-item-name-second">
								<a class="product-item-link"
								   href="<?= /* @escapeNotVerified */
								   $_product->getProductUrl() ?>">
									<?= /* @escapeNotVerified */
									$_helper->productAttribute($_product,
										$_product->getName(), 'name') ?>
								</a>
							</strong>
							<?php // Product Image ?>
							<a href="<?= /* @escapeNotVerified */
							$_product->getProductUrl() ?>"
							   class="product photo product-item-photo"
							   tabindex="-1">
								<?= $productImage->toHtml() ?>
							</a>
							<div class="product details product-item-details">
								<?php if ($viewMode == 'list') : ?>
								<div class="product-view-col">
								<?php endif; ?>
								<?php
								$_productNameStripped
									= $block->stripTags($_product->getName(),
									null, true);
								?>
								<strong class="product name product-item-name">
									<a class="product-item-link"
									   href="<?= /* @escapeNotVerified */
									   $_product->getProductUrl() ?>">
										<?= /* @escapeNotVerified */
										$_helper->productAttribute($_product,
											$_product->getName(), 'name') ?>
									</a>
								</strong>
								<?= $block->getReviewsSummaryHtml($_product,
									$templateType) ?>

								<?php //if ($showDescription): ?>
								<div class="product description product-item-description">
									<?= /* @escapeNotVerified */
									$_helper->productAttribute($_product,
										$_product->getShortDescription(),
										'short_description') ?>
									<a href="<?= /* @escapeNotVerified */
									$_product->getProductUrl() ?>"
									   title="<?= /* @escapeNotVerified */
									   $_productNameStripped ?>"
									   class="action more"><?= /* @escapeNotVerified */
										__('Learn More') ?></a>
								</div>
								<?php //endif; ?>

								<?php if ($viewMode == 'list') : ?>
									</div><div class="product-view-col">
								<?php endif; ?>
								<?= /* @escapeNotVerified */
								$block->getProductPrice($_product) ?>
								<?= $block->getProductDetailsHtml($_product) ?>

								<div class="product-item-inner">
									<div class="product actions product-item-actions"<?= strpos($pos,
										$viewMode . '-actions') ? $position
										: '' ?>>
										<div class="actions-primary"<?= strpos($pos,
											$viewMode . '-primary') ? $position
											: '' ?>>
											<?php if ($_product->isSaleable()): ?>
												<?php $postParams
													= $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form"
													  data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
													  action="<?= /* @NoEscape */
													  $postParams['action'] ?>"
													  method="post">
													<input type="hidden"
														   name="product"
														   value="<?= /* @escapeNotVerified */
														   $postParams['data']['product'] ?>">
													<input type="hidden"
														   name="<?= /* @escapeNotVerified */
														   Action::PARAM_NAME_URL_ENCODED ?>"
														   value="<?= /* @escapeNotVerified */
														   $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
													<?= $block->getBlockHtml('formkey') ?>
													<?php $qty = ($block->getProductDefaultQty() == 0) ? 1 :
													 $block->getProductDefaultQty(); ?>
													<input type="number"
														   name="qty"
														   maxlength="4"
														   value="<?php /* @escapeNotVerified */ echo $qty ?>"
														   title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty form-control"
														   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
													/>
													<button type="submit"
															title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
															class="action tocart primary">
														<span><?= /* @escapeNotVerified */
															__('Add to Cart') ?></span>
													</button>
												</form>
											<?php else: ?>
												<?php if ($_product->isAvailable()): ?>
													<div class="stock available">
														<span><?= /* @escapeNotVerified */
															__('In stock') ?></span>
													</div>
												<?php else: ?>
													<div class="stock unavailable">
														<span><?= /* @escapeNotVerified */
															__('Out of stock') ?></span>
													</div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
										<?php /*<div data-role="add-to-links"
											 class="actions-secondary"<?= strpos($pos,
											$viewMode . '-secondary')
											? $position : '' ?>>
											<?php if ($addToBlock
												= $block->getChildBlock('addto')
											): ?>
												<?= $addToBlock->setProduct($_product)
													->getChildHtml() ?>
											<?php endif; ?>
										</div>*/ ?>
									</div>
								</div>
								<?php if ($viewMode == 'list') : ?>
									</div>
								<?php endif; ?>
							</div>
						</div>
					</li>
				<?php endforeach; ?>
			</ol>
		</div>
	<?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
		<?php if (! $block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {
						"product_sku": "<?= /* @NoEscape */
				$_product->getSku() ?>"
					}
				}
			}

			</script>
		<?php endif; ?>
	<?php endif; ?>
<?php endif; /*if($block->level() == 3) :*/
