<?php
# 2024-03-10 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/header.phtml`":
# https://github.com/cabinetsbay/site/issues/105
use Magento\Catalog\Model\Category as C;
use Sharapov\Cabinetsbay\Block\Category\View as B;
/** @var B $block */ $b = $block; /** @var B $b */
$c = $b->getCurrentCategory(); /** @var C $c */
# 2024-03-10
# 2.1) Level 0: «Root Catalog».
# 2.2) Level 1: «Default Category».
# 2.3) Level 2:
# 		«Ready to Assemble Cabinets»
# 		«Pre-Assembled Cabinets»
# 		«Cabinet Organizers & Hardware»
# 2.4) Level 3: «Steam White Shaker».
if (cb_category_is_l2($c)) {
	?><h1 class="page-title"><?= $c->getName(); ?></h1><?php
}
else {
	# 2024-03-11 Dmitrii Fediuk https://upwork.com/fl/mage2pro
	# "On frontend category pages of levels 3 and below, the name of a higher level category is mistakenly used for the H1 tag":
	# https://github.com/cabinetsbay/site/issues/107
	/** @var string $title */
	$title = df_tag('h1', 'page-title', implode([$c->getName(), df_tag('sub', [], $c->getParentCategory()->getName())]));
	# 2024-03-11 Dmitrii Fediuk https://upwork.com/fl/mage2pro
	# 1) "The `H1` tag is duplicated on the frontend category pages": https://github.com/cabinetsbay/site/issues/104
	# 2) "Category names are not shown on narrow screens": https://github.com/cabinetsbay/site/issues/108
	# 3) It is visible on narrow screens only.
	echo $title;
	echo df_block_output('CabinetsBay_Core', 'catalog/category/tabs', ['b' => $b, 'title' => $title]);
	?>
<?php
}
if ($b->isContentMode() || $b->isMixedMode()) {
	?><div class="category-cms"><?= $b->getCmsBlockHtml() ?></div><?php
}