<?php
# 2024-03-13 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/view.phtml`":
# https://github.com/cabinetsbay/site/issues/112
use Magento\Catalog\Helper\Category as H;
use Sharapov\Cabinetsbay\Block\Category\View as B;
/** @var B $block */ $b = $block; /** @var B $b */
$h = df_category_h(); /** @var H $h */
if (2 === $b->level()) {
	echo df_block_output('CabinetsBay_Core', 'catalog/category/l2/faq', ['b' => $b]);
	echo df_block_output('CabinetsBay_Core', 'catalog/category/l2/l3', ['b' => $b]);
	if ($b->isRTA()) {
	  print '<div id="faq-purchase" class="product-page-faq">';
	  print strip_tags($b->getLayout()->createBlock('Magento\Cms\Block\Block')
						 ->setBlockId('product-page-faq-rta-welcome')->toHtml(), '<p><h3>');
	  print '</div>';
	  print '<div class="product-page-faq">';
	  print strip_tags($b->getLayout()->createBlock('Magento\Cms\Block\Block')
						 ->setBlockId('product-page-faq-rta-body')->toHtml(), '<p><h4><strong>');
	  print '</div>';
	  print '<div id="how-to-shop" class="product-page-how-to-shop mobile-view">';
	  print strip_tags($block
						 ->getLayout()
						 ->createBlock('Magento\Cms\Block\Block')
						 ->setBlockId('product-page-rta-how-to-shop')
						 ->toHtml(), '<p><h3>');
	  print '<a href="#products_list" class="scrollTo">Click here to start shopping</a>';
	  print '</div>';
	  print '<div class="product-page-info mobile-view">';
	  print strip_tags($block
						 ->getLayout()
						 ->createBlock('Magento\Cms\Block\Block')
						 ->setBlockId('product-page-rta-info')
						 ->toHtml(), '<p><strong><a><table><tbody><tr><td><h3>');
	  print '</div>';
	}
	elseif ($b->isPA()) { // If pre-assembled products
	  print '<div id="faq-purchase" class="product-page-faq">';
	  print strip_tags($b->getLayout()->createBlock('Magento\Cms\Block\Block')
						 ->setBlockId('product-page-faq-pa-welcome')->toHtml(), '<p><h3>');
	  print '</div>';
	  print '<div class="product-page-faq">';
	  print strip_tags($b->getLayout()->createBlock('Magento\Cms\Block\Block')
						 ->setBlockId('product-page-faq-pa-body')->toHtml(), '<p><h4><strong>');
	  print '</div>';
	  print '<div id="how-to-shop" class="product-page-how-to-shop mobile-view">';
	  print strip_tags($block
						 ->getLayout()
						 ->createBlock('Magento\Cms\Block\Block')
						 ->setBlockId('product-page-pa-how-to-shop')
						 ->toHtml(), '<p><h3>');
	  print '<a href="#products_list" class="scrollTo">Click here to start shopping</a>';
	  print '</div>';
	  print '<div class="product-page-info mobile-view">';
	  print strip_tags($block
						 ->getLayout()
						 ->createBlock('Magento\Cms\Block\Block')
						 ->setBlockId('product-page-pa-info')
						 ->toHtml(), '<p><strong><a><table><tbody><tr><td><h3>');
	  print '</div>';
	}
}
elseif (3 <= $b->level()) {
	$sndLevelCategories = $b->l3();
	if ($sndLevelCategories) {
		$subCategories = $sndLevelCategories->getChildrenCategories()->addAttributeToFilter('include_in_menu', 1);
	}
	else {
		$subCategories = [];
	}
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	if (count($subCategories) > 0) { ?>
		<div class="category-filterblock">
			<?php foreach ($subCategories as $subCategory) { ?>
				<div style="width: calc(100%/<?=count($subCategories);?>);">
					<div class="category-filter-dropdown" data-mage-init='{"dropdown":{}}'>
						<span
							class="action toggle"
							data-toggle="dropdown"
							aria-haspopup="true"
							data-category-url="<?= $h->getCategoryUrl($subCategory);?>"
						><span><?= $subCategory->getName() ?></span></span>
						<ul class="dropdown">
							<li>
								<span class="item" onclick="window.location.href='<?= $h->getCategoryUrl($subCategory);?>'" data-category-url="<?= $h->getCategoryUrl($subCategory);?>">Show all <?= $subCategory->getName() ?></span>
							</li>
							<?php if (count($subCategory->getChildrenCategories()) > 0) { ?>
							  <?php foreach ($subCategory->getChildrenCategories() as $subCategory2) { ?>
								  <li>
									  <span class="item" onclick="window.location.href='<?= $h->getCategoryUrl($subCategory2);?>'" data-category-url="<?= $h->getCategoryUrl($subCategory2);?>"><?= $subCategory2->getName() ?></span>
								  </li>
							  <?php } ?>
							<?php  } ?>
						</ul>
					</div>
				</div>
			<?php } ?>
		</div>
	<?php
	}
}