<?php
# 2024-03-13 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/view.phtml`":
# https://github.com/cabinetsbay/site/issues/112
use Magento\Catalog\Helper\Category as H;
use Sharapov\Cabinetsbay\Block\Category\View as B;
/** @var B $block */ $b = $block; /** @var B $b */
$h = df_category_h(); /** @var H $h */
if (2 === $b->level()) {
	echo df_block_output('CabinetsBay_Core', 'catalog/category/l2/top', ['b' => $b]);
	echo df_block_output('CabinetsBay_Core', 'catalog/category/l2/l3', ['b' => $b]);
	echo df_block_output('CabinetsBay_Core', 'catalog/category/l2/bottom', ['b' => $b]);
}
elseif (3 <= $b->level()) {
	$sndLevelCategories = $b->l3();
	if ($sndLevelCategories) {
		$subCategories = $sndLevelCategories->getChildrenCategories()->addAttributeToFilter('include_in_menu', 1);
	}
	else {
		$subCategories = [];
	}
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	if (count($subCategories) > 0) { ?>
		<div class="category-filterblock">
			<?php foreach ($subCategories as $subCategory) { ?>
				<div style="width: calc(100%/<?=count($subCategories);?>);">
					<div class="category-filter-dropdown" data-mage-init='{"dropdown":{}}'>
						<span
							class="action toggle"
							data-toggle="dropdown"
							aria-haspopup="true"
							data-category-url="<?= $h->getCategoryUrl($subCategory);?>"
						><span><?= $subCategory->getName() ?></span></span>
						<ul class="dropdown">
							<li>
								<span class="item" onclick="window.location.href='<?= $h->getCategoryUrl($subCategory);?>'" data-category-url="<?= $h->getCategoryUrl($subCategory);?>">Show all <?= $subCategory->getName() ?></span>
							</li>
							<?php if (count($subCategory->getChildrenCategories()) > 0) { ?>
							  <?php foreach ($subCategory->getChildrenCategories() as $subCategory2) { ?>
								  <li>
									  <span class="item" onclick="window.location.href='<?= $h->getCategoryUrl($subCategory2);?>'" data-category-url="<?= $h->getCategoryUrl($subCategory2);?>"><?= $subCategory2->getName() ?></span>
								  </li>
							  <?php } ?>
							<?php  } ?>
						</ul>
					</div>
				</div>
			<?php } ?>
		</div>
	<?php
	}
}