<?php
/**
 * @copyright Sharapov A. <alexander@sharapov.biz>
 * @link      http://www.sharapov.biz/
 * @license   https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License
 * Date: 07/10/2019
 * Time: 18:19
 */
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt(); ?>
<?php $isHome = $block->getUrl('') == $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
if($isHome) : ?>
    <span class="logo">
        <img src="<?=/* @escapeNotVerified */
        $block->getLogoSrc()?>"
             title="<?=$block->escapeHtmlAttr($block->getLogoAlt())?>"
             alt="<?=$block->escapeHtmlAttr($block->getLogoAlt())?>"
            <?=$block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : ''?>
            <?=$block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : ''?>
        />
    </span>
<?php else : ?>
    <a class="logo" href="<?=$block->getUrl('')?>" title="<?=/* @escapeNotVerified */
    $storeName?>">
        <img src="<?=/* @escapeNotVerified */
        $block->getLogoSrc()?>"
             title="<?=$block->escapeHtmlAttr($block->getLogoAlt())?>"
             alt="<?=$block->escapeHtmlAttr($block->getLogoAlt())?>"
            <?=$block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : ''?>
            <?=$block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : ''?>
        />
    </a>
<?php endif; ?>
