<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="block newsletter">
    <div class="content">
      <span>Sign up for sales & promotions today!<span>Enter your email and click "Done"!</span></span>
      <span>
        <form class="form subscribe"
              novalidate
              action="<?=$block->escapeUrl($block->getFormActionUrl())?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label"
                       for="newsletter"><span><?=$block->escapeHtml(__('Sign Up for Our Newsletter:'))?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                           placeholder="<?=$block->escapeHtml(__('your@email.com'))?>"
                           data-mage-init='{"mage/trim-input":{}}'
                           data-validate="{required:true, 'validate-email':true}" />
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe" title="<?=$block->escapeHtmlAttr(__('Subscribe'))?>"
                        type="submit">
                    <span><?=$block->escapeHtml(__('Done'))?></span>
                </button>
            </div>
        </form>
      </span>
    </div>
</div>
