<?php
/** @var $block \Magento\Weee\Block\Item\Price\Renderer */
$item = $block->getItem();
// ensure we use the zone for the shopping cart / minicart
$_helper = $this->helper('WeltPixel\QuickCart\Helper\Data');
$originalZone = $block->getZone();
$block->setZone(\Magento\Framework\Pricing\Render::ZONE_CART);
$isDiscountedPriceEnabled = (int)$_helper->isQuickCartDiscountedPriceEnabled();
$discountedPriceDisplayMode = $_helper->getQuickCartDiscountDisplayMode();
$priceWrapper = '<span class="minicart-price">';
$finalPriceWrapper = '';
if ($isDiscountedPriceEnabled) {
    $finalPrice = $item->getProduct()->getFinalPrice();
    $normalPrice = $item->getProduct()->getPrice();
    if ($normalPrice != $finalPrice) {
        $priceWrapper = '<span class="minicart-price final-price">';
        $finalPriceWrapper .= '<span class="minicart-old-price">' . $block->formatPrice($normalPrice) . '</span>';
    }
}
?>
<?php if ($block->displayPriceInclTax() || $block->displayBothPrices()) : ?>
    <span class="price-including-tax" data-label="<?= $block->escapeHtmlAttr(__('Incl. Tax')) ?>">
<?php # 2024-04-26 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Disable the unused `Magento_Weee` module": https://github.com/cabinetsbay/site/issues/144 ?>
		<span class="minicart-price">
			<?= /* @noEscape */ $block->formatPrice($block->getUnitDisplayPriceInclTax()) ?>
		</span>
<?php # 2024-04-26 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Disable the unused `Magento_Weee` module": https://github.com/cabinetsbay/site/issues/144 ?>
    </span>
<?php endif; ?>

<?php if ($block->displayPriceExclTax() || $block->displayBothPrices()) : ?>
    <span class="price-excluding-tax <?php echo $discountedPriceDisplayMode ?>" data-label="<?= $block->escapeHtmlAttr(__('Excl. Tax')) ?>">
<?php # 2024-04-26 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Disable the unused `Magento_Weee` module": https://github.com/cabinetsbay/site/issues/144 ?>
		<?php echo $priceWrapper ?>
		<?= /* @noEscape */ $block->formatPrice($block->getUnitDisplayPriceExclTax()) ?>
	</span>

    <?php echo $finalPriceWrapper ?>
    </span>
<?php endif; ?>
<?php $block->setZone($originalZone); ?>