<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<?php $qty = ($block->getProductDefaultQty() == 0) ? 1 : $block->getProductDefaultQty(); ?>
<p class="affirm-as-low-as" data-page-type="product" data-amount="<?php print number_format($_product->getFinalPrice(), 2, '', ''); ?>"></p>
<div class="box-tocart">
  <b>Qty:</b> <input type="number"
         name="qty"
         maxlength="4"
         value="<?php /* @escapeNotVerified */ echo $qty ?>"
         title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty form-control"
         data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
  /><br /><br />
    <div class="fieldset">
        <div class="actions">
            <button type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
