<?php
# 2024-05-06 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Refactor `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Theme/templates/homepage.phtml`":
# https://github.com/cabinetsbay/site/issues/146
use Sharapov\Cabinetsbay\Block\HomePage as B;
/** @var B $block */ $b = $block; /** @var B $b */
?>
<div class="homepage-grid">
	<?= df_cms_block('home-page-slider') ?>
	<div class="homepage-why-us">
		<?= df_cc_n(df_cms_block('home-page-why-us'), df_cms_block('home-page-why-us-icon-block')) ?>
	</div>
	<div class="homepage-popular c-products-grid">
		<?php /** @var \Magento\Catalog\Helper\Category $categoryHelper_sub */
		$categoryHelper_sub = $this->helper('Magento\Catalog\Helper\Category'); ?>
		<?php $popularProductsCollection = $b->getPopularProducts(); ?>
		<?php if (count($popularProductsCollection) > 0) : ?>
			<?php print $b
				->getLayout()
				->createBlock('Magento\Cms\Block\Block')
				->setBlockId('home-page-popular-kitchen')
				->toHtml();
			print '<ul>';
			foreach ($popularProductsCollection as $popularProduct) {
				/** @var \Magento\Catalog\Model\Category\Interceptor $popularProduct */
				print '<li>';
				print '<a href="' . $categoryHelper_sub->getCategoryUrl($popularProduct) . '">';
				print '<div>' . $popularProduct->getName() . '</div>';
				if($popularProduct->getData('cb_kitchen_set') != '') {
				  print '<div class="size-price"><b>' . $popularProduct->getData('cb_kitchen_set') . '</b>' . $popularProduct->getData('cb_kitchen_price') . '</div>';
				}
				try {
					print '<img src="' . $popularProduct->getImageUrl() . '" border="0" />';
				} catch (\Magento\Framework\Exception\LocalizedException $e) {

				}
				print '</a>';
				print '<div><a href="' . $categoryHelper_sub->getCategoryUrl($popularProduct)
					. '">Shop cabinets</a><a href="'.$popularProduct->getData('cb_door_sample_link').'">Order sample</a></div>';
				print '</li>';
			}
			print '</ul>';
		endif; /*if(count($popularProductsCollection) > 0)*/ ?>
	</div>
	<div class="homepage-workflow">
		<?= $b->getLayout()->createBlock('Magento\Cms\Block\Block')
			->setBlockId('home-page-project-workflow')->toHtml(); ?>
	</div>
	<div class="homepage-affirm-banner">
	  <a href="/financing.html"><img src="<?php print $b->getViewFileUrl('images/affirm_banner.svg');?>" /></a>
	</div>
	<div class="homepage-affirm-banner-mobile">
	  <a href="/financing.html"><img src="<?php print $b->getViewFileUrl('images/affirm_banner_mob.svg');?>" /></a>
	</div>
	<div class="homepage-call-us">
		<div class="left">
			<div class="call-us-block">
				<h4>Call Us Today</h4>
				<h4><?= trim(strip_tags($b->getLayout()
						->createBlock('Magento\Cms\Block\Block')
						->setBlockId('block-header-top-phone')
						->toHtml(), '<a>')); ?></h4>
			</div>
			<div><?= trim(strip_tags($b->getLayout()
					->createBlock('Magento\Cms\Block\Block')
					->setBlockId('home-page-schedule')
					->toHtml(), '<br>')); ?></div>
		</div>
		<div class="right">
			<div class="catalog-links">
				<div>
					<?= trim(strip_tags($b->getLayout()
						->createBlock('Magento\Cms\Block\Block')
						->setBlockId('home-page-catalog-links')
						->toHtml(), '<a><ul><li>')); ?>
				</div>
			</div>
		</div>
	</div>
</div>